GRANT SELECT ON V_DASHBOARD_REGIOES_SAUDE TO ALGOMED;
GRANT SELECT ON V_HISTORICO_INTERNACOES TO ALGOMED;
GRANT SELECT ON V_INFRAESTRUTURA_HOSPITALAR_2025 TO ALGOMED;
GRANT SELECT ON V_DASHBOARD_MUNICIPIOS_SAUDE TO ALGOMED;

GRANT EXECUTE ON DBMS_CLOUD TO ALGOMED;
GRANT EXECUTE ON DBMS_CLOUD_AI TO ALGOMED;
