CREATE OR REPLACE VIEW ADMIN.V_DASHBOARD_MUNICIPIOS_SAUDE AS
SELECT
    L.MUNICIPIO,
    R.REGIAO_SAUDE,
    SUM(L.LEITOS_EXISTENTES) AS LEITOS_EXISTENTES,
    SUM(L.LEITOS_SUS) AS LEITOS_SUS,
    SUM(L.UTI_TOTAL_EXIST) AS UTIS_EXISTENTES,
    SUM(L.UTI_TOTAL_SUS) AS UTIS_SUS
FROM ADMIN.LEITOS_2025 L
JOIN ADMIN.MUNICIPIOS_SP_REGIOES_SAUDE R
  ON REGEXP_REPLACE(
       TRANSLATE(
         UPPER(TRIM(L.MUNICIPIO)),
         'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
         'AAAAAEEEEIIIIOOOOOUUUUC'
       ),
       '[^A-Z0-9]',
       ''
     )
   =
     REGEXP_REPLACE(
       TRANSLATE(
         UPPER(TRIM(R.MUNICIPIO)),
         'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
         'AAAAAEEEEIIIIOOOOOUUUUC'
       ),
       '[^A-Z0-9]',
       ''
     )
WHERE UPPER(TRIM(L.UF)) = 'SP'
  AND L.COMP = 202512
GROUP BY
    L.MUNICIPIO,
    R.REGIAO_SAUDE;
